catalog/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('',views.index,name='index'),
    path('books/',views.BookListView.as_view(),name='books'),
    path('books/<int:pk>',views.BookDetailView.as_view(),name='book-detail'),
    path('authors/',views.AuthorListView.as_view(),name='authors'),
    path('authors/<int:pk>',views.AuthorDetailView.as_view(),name='author-detail'),
    path('mybooks/',views.LoanedBooksByUserListView.as_view(),name='my-borrowed'),
    path('all_borrowed_books/',views.AllBorrowedBooks.as_view(),name='all-borroweds'),
    path('books/<uuid:pk>/renew/',views.renew_book_librarian,name='renew-book-librarian'),
    path('authors/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('authors/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('authors/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('books/create/',views.BookCreate.as_view(),name='book-create'),
    path('books/<int:pk>/update/',views.BookUpdate.as_view(),name='book-update'),
    path('books/<int:pk>/delete/',views.BookDelete.as_view(),name='book-delete')
]

locallibrary_django/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/',include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/',include('django.contrib.auth.urls'))
]
# server the static files because Django does not serve them by default
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models/author.py
from django.db import models
from django.urls import reverse
class Author(models.Model):

    first_name = models.CharField(max_length=100)

    last_name = models.CharField(max_length=100)

    date_of_birth= models.DateField(null=True,blank=True)

    date_of_death = models.DateField('Died',null=True,blank=True)

    class Meta:
        ordering =['last_name','first_name']
    
    def get_absolute_url(self):
        return reverse('author-detail',args=[str(self.id)])

    def __str__(self):
        return f'{self.first_name}, {self.last_name}'

catalog/models/book.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
class Book(models.Model):
    # title fo the book
    title = models.CharField(max_length=200)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author',on_delete=models.SET_NULL,null=True)

    summary = models.TextField(max_length=1000,help_text='Enter a brief description of the book')

    isbn = models.CharField('ISBN',max_length=13,unique=True,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    genre = models.ManyToManyField('Genre', help_text='Select a genre for this book')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail',args=[str(self.id)])

    def display__genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display__genre.short_description = 'Genre'

    

catalog/models/book_instance.py
from django.db import models
import uuid
from django.contrib.auth.models import User
from datetime import date
class BookInstance(models.Model):
    
    id =  models.UUIDField(primary_key=True,default=uuid.uuid4,help_text='Unique ID for this particular book across whole library')

    book = models.ForeignKey('Book',on_delete=models.RESTRICT,null=True)

    imprint =  models.CharField(max_length=200)

    due_back = models.DateField(null=True,blank=True)

    LOAN_STATUS=(
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1,choices=LOAN_STATUS,blank=True,default='m',help_text='Book availability')

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['due_back']
        permissions =  (("can_mark_returned", "Set book as returned"),)
    
    def __str__(self):
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

catalog/models/genre.py
from django.db import models

# Create your models here.
class Genre(models.Model):
    # modal representing the book genre
    name = models.CharField(max_length=200,help_text='Enter a book genre (e.g. Science Fiction)')
    def __str__(self):
        # String for respresenting the Model object
        return self.name

catalog/models/language.py
from django.db import models

class Language(models.Model):

    name = models.CharField(max_length=100)

    book = models.ForeignKey('Book',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

catalog/forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text='Enter a date between now and 4 weeks (default 3).')

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        
        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today()+ datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        # Remember to always return the cleaned data.
        return data

catalog/views.py
from django.shortcuts import render

# Create your views here.

catalog/views/AuthorDetailView.py
from django.views import generic 
from catalog.models import Author 

class AuthorDetailView(generic.DetailView):
    model = Author

catalog/views/AuthorListView.py
from django.views import generic
from catalog.models import Author

class AuthorListView (generic.ListView):
    model = Author

catalog/views/BookDetailView.py
from django.views import generic
from catalog.models import Book

class BookDetailView(generic.DetailView):
    model = Book

    
    

catalog/views/BookListView.py
from django.views import generic
from catalog.models import Book

class BookListView(generic.ListView):
    model=Book
    paginate_by = 2
    # by default here will be book_list I just change to my_book_list
    # context_object_name = 'my_book_list'
    # queryset = Book.objects.filter(title__icontains='harry')[:5] # Get 5 books containing the title war
    # template_name = 'books/my_arbitrary_template_name_list.html'  # Specify your own template name/location
    # def get_queryset(self):
    #     return  Book.objects.filter(title__contains='war')[:5] # Get 5 books containing the title war

    # def get_context_data(self,**kwargs):
    #     # Call the base implementation first to get the context
    #     # get the existing context from our superclass.
    #     context = super(BookListView,self).get_context_data(**kwargs)
    #     # Create any data and add it to the context
    #     context['some_data'] = 'This is just some data'
    #     return context

catalog/views/RenewBookInstanceModelForm.py
from django.forms import ModelForm

from catalog.models import BookInstance

class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
       data = self.cleaned_data['due_back']

       # Check if a date is not in the past.
       if data < datetime.date.today():
           raise ValidationError(_('Invalid date - renewal in past'))

       # Check if a date is in the allowed range (+4 weeks from today).
       if data > datetime.date.today() + datetime.timedelta(weeks=4):
           raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

       # Remember to always return the cleaned data.
       return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

catalog/views/RenewBookLibrairan.py
import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.forms import RenewBookForm

from catalog.models import BookInstance

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)

def renew_book_librarian(request,pk):
    book_instance = get_object_or_404(BookInstance,pk=pk)
    # If this is a POST request then process the Form data
    if request.method == 'POST' :
        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)
        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            #you can use request.POST['renewal_date'] or request.GET['renewal_date'] but it's not recommended
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borroweds') )
    # If this is a GET (or any other method) create the default form
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form':form,
        'book_instance':book_instance
    }

    return render(request, 'catalog/book_renew_librarian.html',context)

catalog/views/all_borrowed_books.py
from catalog.models import BookInstance
from django.contrib.auth.mixins import PermissionRequiredMixin,LoginRequiredMixin
from django.views import generic
# from django.contrib.auth.mixins import LoginRequiredMixin
class AllBorrowedBooks(LoginRequiredMixin,PermissionRequiredMixin,generic.ListView):
    model = BookInstance
    permission_required='catalog.can_mark_returned'
    template_name =  'catalog/all_borrowed_books.html'

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

catalog/views/borrowed_book.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from catalog.models import BookInstance
class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'

    def get_queryset(self):
         return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

catalog/views/create_update_delete_author.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from catalog.models import Author

class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/06/2020'}

class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__' # Not recommended (potential security issue if more fields added)

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

catalog/views/create_update_delete_book.py
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse_lazy

from catalog.models import Book

class BookCreate(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    model = Book
    permission_required='catalog.can_mark_returned'
    fields = '__all__'


class BookUpdate(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    model = Book
    permission_required='catalog.can_mark_returned'
    fields =  '__all__' # Not recommended (potential security issue if more fields added)



class BookDelete(LoginRequiredMixin,PermissionRequiredMixin,DeleteView):
    model = Book
    permission_required='catalog.can_mark_returned' 
    success_url = reverse_lazy('books')

catalog/views/index.py
from django.shortcuts import render
from catalog.models import Author, Book, BookInstance, Genre


def index(request):
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status='a').count() 

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    hp_books = Book.objects.filter(title__icontains='harry').count()
    # get the value of the 'num_visits' session key if does not exsit set it to 1
    num_visits = request.session.get('num_visits',1)
    # increment the session key 
    request.session['num_visits'] = num_visits + 1

    #if the key session is an object like a case then 
    # django with not recognize the changes if you made a change 
    # so you have to explicitly mark the session as having been modified.
    # Set session as modified to force data updates/cookie to be saved.
    
    # request.session.modified = True

    #context to send to the tamplate
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'hp_books': hp_books,
        'num_visits':num_visits
    }

    return render(request, 'index.html', context=context)

catalog/templates/catalog/all_borrowed_books.html
{% extends 'base_generic.html' %} 

{% block content %}
    <h1>All Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})-{{bookinst.borrower.username}} 
        {% if perms.catalog.can_mark_returned %}<a href="{% url 'renew-book-librarian' bookinst.id %}" > -Renew</a>{% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Author: {{author}}</h1>
    <h5 class="text-secondary">
        ({{author.date_of_birth}} 
        {% if author.date_of_death %}
        - {{author.date_of_death}}
        {% endif %}
        )
        {%if perms.catalog.can_mark_returned %}
                <a href="{% url 'author-update' author.pk %}">Edit</a>|<a href="{% url 'author-delete' author.pk %}">Delete</a>
        {% endif %}
    </h5>
    <div style="margin-left:20px;margin-top:20px">
      <h4>Books</h4>
      {% for book in author.book_set.all %} 
      <hr>
        <h3><a href="{% url 'book-detail' book.pk %}">{{book.title}}</a>({{book.bookinstance_set.count}}) </h3>
        <p>
            {{book.summary}}
        </p>
      {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends 'base_generic.html' %}


{% block content %}
    <h1>Author List</h1>
    {% if author_list %}
        <ul>
            {% for author in author_list %}
            <li>
                <a href="{{author.get_absolute_url}}">{{ author }}</a> ({{author.date_of_birth}} 
                {% if author.date_of_death %}
                - {{author.date_of_death}}
                {% endif %}
                )
                {%if perms.catalog.can_mark_returned %}
                <a href="{% url 'author-update' author.pk %}">Edit</a>|<a href="{% url 'author-delete' author.pk %}">Delete</a>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    {% else %}
         <p>There are no Authors in the library.</p>
    {% endif %} 
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends 'base_generic.html' %}

{% block content %}
    <div class="d-flex align-items-center">
      <h1 class="mr-4">Title {{book.title}}</h1>  
      {% if perms.catalog.can_mark_returned %}   
      <a style="font-size:20px;" href="{% url 'book-update' book.pk %}">Edit</a>|<a style="font-size:20px;" href="{% url 'book-delete' book.pk %}">Delete</a>
      {% endif %}
    </div>
    <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{book.language_set.all |join:", " }}</p>
    <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>
  
    <div style="margin-left:20px;margin-top:20px">
      <h4>Copies</h4>
  
      {% for copy in book.bookinstance_set.all %} 
      <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
          {{ copy.get_status_display }}
        </p>
        {% if copy.status != 'a' %}
          <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
        {% endif %}
        <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
        <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
      {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends 'base_generic.html' %} 

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends 'base_generic.html' %}


{% block content %}
    <h1 class="mr-4">Book List</h1>     
    {% if book_list %}
        <ul>
            {% for book in book_list %}
            <li>
                <a href="{{book.get_absolute_url}}">{{ book.title }}</a> ({{book.author}}) 
                {% if perms.catalog.can_mark_returned %}
                <a  href="{% url 'book-update' book.pk %}">Edit</a>|<a  href="{% url 'book-delete' book.pk %}" >Delete</a>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    {% else %}
         <p>There are no books in the library.</p>
    {% endif %} 
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends 'base_generic.html' %} 
{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}